easybuilders/easybuild

docs/Changelog.rst, docs/Configuration.rst, docs/conf.py
replaces #70 and targets `develop`
=> mention need to escape % when configuring log file format via configuration file

docs/Changelog.rst, docs/Configuration.rst, docs/conf.py
rendered version at https://boegel-eb.readthedocs.org/en/XDG_CONFIG/Configuration.html#configuration-file-s
@JensTimmerman, @fgeorgatos, @wpoely86: please review
=> extend section on (default) EasyBuild configuration files to also cover $XDG_CONFIG_DIRS

docs/Changelog.rst, docs/Writing_easyconfig_files.rst, docs/conf.py
This should've been changed ages ago, since the fallback has been disabled since EB v2.0...
@wpoely86: please review?
=> fix documentation w.r.t. easyblock parameter, no more fallback to ConfigureMake

docs/Changelog.rst, docs/Experimental_features.rst, docs/Manipulating_dependencies.rst, docs/Writing_easyconfig_files.rst, docs/conf.py
preview available at http://boegel-eb.readthedocs.org/en/minimal_toolchains/Manipulating_dependencies.html#using-minimal-toolchains-for-dependencies
@ocaisa: please review?
=> document experimental support for minimal toolchains

docs/Changelog.rst, docs/Configuration.rst, docs/conf.py
preview at http://boegel-eb.readthedocs.org/en/show_config/Configuration.html
=> add new docs section on --show-config

docs/Writing_easyconfig_files.rst, docs/scripts/update-all-docs.sh
the script assumes it is run from the `docs` folder
Depends on the scripts in ~~https://github.com/hpcugent/easybuild/pull/132~~ and ~~https://github.com/hpcugent/easybuild/pull/139~~ plus the rst support from https://github.com/hpcugent/easybuild-framework/pull/1339.
=> Script to update all automatically generated documentation

docs/Changelog.rst, docs/Deprecated-functionality.rst, docs/conf.py
see http://boegel-eb.readthedocs.io/en/deprecated_easyblock_functions/Deprecated-functionality.html#depr-lapack-get-blas-lib
=> add documentation on deprecated functions provided by easyblocks

docs/Changelog.rst, docs/Release_notes.rst, docs/conf.py
depends on:
edit: preview at http://boegel-eb.readthedocs.io/en/eb300/Release_notes.html
=> update docs & release notes for EasyBuild v3.0

docs/Writing_easyconfig_files.rst
builddependencies = [('CMake', '2.8.12', '', ('GCC', '4.8.2')]
=> Add a missing ")" in an example.

docs/Configuration.rst
The path was not the default configuration file location (though maybe it was in the past).
=> Correct location for example config file

docs/Changelog.rst, docs/Deprecated-functionality.rst, docs/conf.py
preview in http://boegel-eb.readthedocs.io/en/depr_320/Deprecated-functionality.html#overview-of-deprecated-functionality-in-easybuild-version-version
=> document deprecated behaviour in EasyBuild v3.2.0

docs/Changelog.rst, docs/Deprecated-functionality.rst, docs/Writing_easyconfig_files.rst, docs/conf.py
Updated docs for `checksums` and changes in https://github.com/hpcugent/easybuild-framework/pull/2223
preview at http://boegel-eb.readthedocs.io/en/sources_dict/Writing_easyconfig_files.html#source-files-patches-and-checksums and http://boegel-eb.readthedocs.io/en/sources_dict/Deprecated-functionality.html#depr-sources-2-element-tuple
=> document specifying of checksums + alternate (& deprecated) format for sources

setup.py
Recent versions of setuptools require the `description` field to be a single line, or else:
```
Upload failed (400): summary: Multiple lines are not allowed.
error: Upload failed (400): summary: Multiple lines are not allowed.
```
=> use single-line description in setup.py

docs/Backup_modules.rst, docs/Changelog.rst, docs/Partial_installations.rst, docs/Using_the_EasyBuild_command_line.rst, docs/conf.py, docs/index.rst
Support for `--backup-modules` was merged to be included in EasyBuild v3.4.0 in https://github.com/easybuilders/easybuild-framework/pull/2134.
This leverages #365; since @damianam is on leave I looked into extending it a bit.
Preview at http://boegel-eb.readthedocs.io/en/backup_modules/Backup_modules.html
=> document --backup-modules

docs/Contributing.rst
`:ref:` can't be used within a formatted piece of text...
=> fix broken ref in Contributing page

docs/Writing_easyconfig_files.rst
fix for mistake in docs reported by @ paddyoneill in https://github.com/easybuilders/easybuild-framework/issues/2473
=> fix documented order of type/value in checksum tuple

docs/Integration_with_GitHub.rst
I propose to add this minor remark in the github integration docs, it might be obvious but it is not explicitly mentioned in the docs.
=> remark that git-working-dirs-path option can be set in the config file

docs/Changelog.rst, docs/Writing_easyconfig_files.rst, docs/conf.py
preview @ https://boegel-eb.readthedocs.io/en/git_config/Writing_easyconfig_files.html#downloading-from-a-git-repository
@mboisson: please review?
=> document support for downloading sources directly from a Git repository

docs/Changelog.rst, docs/Wrapping_dependencies.rst, docs/conf.py, docs/index.rst
see also:
* framework supports for generating `.modulerc`: https://github.com/easybuilders/easybuild-framework/pull/2575
* `ModuleRC` easyblock: https://github.com/easybuilders/easybuild-easyblocks/pull/1503
* `Java/1.8` wrapper: https://github.com/easybuilders/easybuild-easyconfigs/pull/6712
preview @ https://boegel-eb.readthedocs.io/en/java_wrapper/Wrapping_dependencies.html
=> document support for creating module 'wrappers' for dependencies

docs/Deprecated-functionality.rst
cfr. https://github.com/easybuilders/easybuild-framework/pull/2644 and https://github.com/easybuilders/easybuild-easyblocks/pull/1341
=> document deprecation of 'skip_symlinks' in adjust_permissions + custom PythonPackage easyconfig paramters

docs/Changelog.rst, docs/Deprecated-easyconfigs.rst, docs/conf.py, docs/index.rst
see also https://github.com/easybuilders/easybuild-framework/pull/2656
=> add documentation on deprecated easyconfigs/toolchains

docs/Manipulating_dependencies.rst
@mboisson: updated docs for enhanced `--filter-deps` in https://github.com/easybuilders/easybuild-framework/pull/2357
preview available at https://boegel-eb.readthedocs.io/en/filter_deps_versions/Manipulating_dependencies.html#filtering-dependencies-based-on-version
=> document support for filtering dependencies by version

docs/Deprecated-functionality.rst
@bartoldeman Companion PR for https://github.com/easybuilders/easybuild-framework/pull/2674
=> document deprecation of Toolchain.add_dependencies

docs/Backup_modules.rst, docs/Configuration.rst, docs/Containers.rst, docs/Detecting_loaded_modules.rst, docs/Hooks.rst, docs/Implementing-easyblocks.rst, docs/Including_additional_Python_modules.rst, docs/Installation.rst, docs/Integration_with_GitHub.rst, docs/Release_notes.rst, docs/Removed-functionality.rst, docs/Submitting_jobs.rst, docs/Unit-tests.rst, docs/Using_external_modules.rst, docs/Using_the_EasyBuild_command_line.rst, docs/Writing_yeb_easyconfig_files.rst, docs/demos/scripts/configuring.script, docs/version-specific/generic_easyblocks.rst
Use the codespell python package to spell check the docs, see https://github.com/codespell-project/codespell for details.
I didn't clean `Supported_software.rst` since that is dynamically generated (I think).
=> Run codespell on docs

docs/Containers.rst
Covers changes made in:
* https://github.com/easybuilders/easybuild-framework/pull/2907
* https://github.com/easybuilders/easybuild-framework/pull/2909
* https://github.com/easybuilders/easybuild-framework/pull/2910
preview at https://boegel-eb.readthedocs.io/en/containers/Containers.html
=> update documentation on Singuluarity integration w.r.t. recent changes

docs/Deprecated-easyconfigs.rst
cfr. https://github.com/easybuilders/easybuild-easyconfigs/pull/8585 and https://github.com/easybuilders/easybuild-framework/pull/2951
=> document deprecation of toolchains older than gompi/2016a and foss/2016a

docs/Containers.rst
fixes broken link in https://easybuild.readthedocs.io/en/latest/Containers.html#requirements
Reference was broken because it was enclosed in `*...*` (italics) :-/
reported by @geimer
=> fix broken reference in documentation page on container support

docs/Easyconfig-files-local-variables.rst, docs/index.rst
(preview at https://boegel-eb.readthedocs.io/en/local_vars/Easyconfig-files-local-variables.html)
See also https://github.com/easybuilders/easybuild-framework/pull/2938 and https://github.com/easybuilders/easybuild-framework/pull/2968
~~Not finished yet, but this should definitely get done prior to the EasyBuild 4.0 release...~~
=> add documentation on use of local variables in easyconfig files

docs/Backup_modules.rst, docs/Deprecated-functionality.rst, docs/conf.py
* tweak docs on backing up of module files w.r.t. https://github.com/easybuilders/easybuild-framework/pull/3089
* document deprecation of support for using Lmod 6.x and Python 2.6 (cfr. https://github.com/easybuilders/easybuild-framework/pull/3077 & https://github.com/easybuilders/easybuild-framework/pull/3076)
previews:
* https://boegel-eb.readthedocs.io/en/docs_update_eb410/Backup_modules.html
* https://boegel-eb.readthedocs.io/en/docs_update_eb410/Deprecated-functionality.html
=> doc updates for EasyBuild v4.1.0

docs/Integration_with_GitHub.rst
@boegel As discussed in https://github.com/easybuilders/easybuild-easyconfigs/pull/9301#discussion_r347437496 I added the example pip commands (and removed a superflous sub-sentence)
=> Add example pip commands for GitHub integration

.travis.yml
flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
https://flake8.pycqa.org/en/latest/user/error-codes.html
On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead these tests are focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled language but in a dynamic language like Python they result in the script halting/crashing on the user.
* F63 tests are usually about the confusion between identity …
=> Travis CI: Test for Python syntax errors and undefined names

docs/Common-toolchains.rst, docs/Concepts_and_Terminology.rst, docs/index.rst
Per Slack discussion
What do you think of the idea of adding links to these two pages from
https://easybuild.readthedocs.io/en/latest/eb_list_toolchains.html
https://easybuild.readthedocs.io/en/latest/version-specific/toolchain_opts.html
along with some text that they are for more detailed information about toolchains and with a table of contents entry something like "More information about available toolchains"  to this page,
https://easybuild.readthedocs.io/en/latest/Common-toolchains.html
or in the Toolchains section of
https://easybuild.readthedocs.io/en/latest/Concepts_and_Terminology.html#toolchains
I was unable to find links to the two pages with more details via the table of contents, and I think that would help beginners who do not necessarily know the terms well to be able to …
=> add references to more information w.r.t. toolchains + move up link to common toolchains page on landing page

docs/Using_the_EasyBuild_command_line.rst
The current first example uses `[*]` in the `eb -Dr` output, whereas in the legend below the table, it says it will use [+] to indicate that the build is available, EasyBuild will skip building this module.  The other examples were updated to use the `[+]`.
=> fix marker for indicating what is installed in the output of -D

docs/Typical_workflow_example_with_WRF.rst
This is separating out the changes for WRF example from other documentation
changes that were accidentally bundled in PR #603.  Repeating the summary
here.  This should supercede PR #603, which should be declined or closed.  If you would
like me to do so, I surely can, just let me know.
I updated the example output in the Typical workflow example to use EB
4.1.1 and install WRF based on the foss/2018b toolchain. References in
the text have been changed to match the updated output.
Sorry for the confusion and any extra work.
Addressed in this from #603, username changed to `example` everywhere.
=> Updating WRF examples with output from EB 4.1.1 and foss/2018b

docs/Including_additional_Python_modules.rst, docs/Integration_with_GitHub.rst
requires https://github.com/easybuilders/easybuild-framework/pull/3206
preview at https://mdc-easybuild.readthedocs.io/en/include_easyblocks_from_pr/Integration_with_GitHub.html#using-easyblocks-from-pull-requests-include-easyblocks-from-pr
=> add documentation for --include-easyblocks-from-pr

docs/Writing_easyconfig_files.rst
cfr. https://github.com/easybuilders/easybuild-framework/pull/3197
=> document of use 'keep_git_dir' in 'git_config' spec for sources

.readthedocs.yml
restores API docs that went missing (fixes #587)
=> add readthedocs configuration file

docs/Implementing-easyblocks.rst, docs/Writing_easyconfig_files.rst
Explicitly list easyblock 'properties' (which look like data member names) which reference `self.cfg` dictionary entries, and how to use them.  Don't use 'module' qualifier for extensions.
See https://github.com/easybuilders/easybuild/pull/617/files#r449669160
=> Clarify recent self.cfg and extensions documentation

docs/Contributing.rst, docs/Integration_with_GitHub.rst
We're slowly moving away from Travis, switching over to GitHub Actions (see https://github.com/easybuilders/easybuild-easyconfigs/pull/11055), so let's reflect that in the docs...
=> refer to GitHub Actions rather than Travis w.r.t. CI tests

docs/Easyconfigs_index.rst
I tried to run the following example from this page, but it didn't work:
```
$ eb --create-index --index-max-age=0 $HOME/easybuild/cit-hpc-easybuild/easyconfigs
Usage: eb [options] easyconfig [...]
eb: error: Value '--index-max-age=0' starts with a '-'. Use '--create-index=--index-max-age=0' if the value is correct.
```
This does work:
```
$ eb --index-max-age=0 --create-index $HOME/easybuild/cit-hpc-easybuild/easyconfigs
```
And, according to `eb --help`, it should in principle even be `--create-index=$HOME/easybuild/cit-hpc-easybuild/easyconfigs` (in that case, more commands on this page should be fixed)?
=> Fix broken create index command

docs/Installation.rst, docs/Integration_with_GitHub.rst, docs/Using_the_EasyBuild_command_line.rst
The previous becomes `–pr-commit-msg`. This makes it `--pr-commit-msg` and similarly for the other two.
=> Prevent wrong dash appearing in doc

.github/workflows/scripts.yml
The Ubuntu 20 that GitHub has started using has the `lua/5.2/posix.so` file (or link) in it already, so the script that creates it unconditionally for Ubuntu 18 fails because it exists.
Wrapped the `ln` command in an if so that it only tried to create the symlink if the target does not exist.
=> Adding conditional symlinking of lua posix lib in GH workflow script

docs/Integration_with_GitHub.rst
While regenerating my GitHub token (due to the recent changes) I looked at the [scopes](https://docs.github.com/en/developers/apps/scopes-for-oauth-apps) we've documented as needed. I am fairly sure that we only require:
* `public_repo` (to be able to read/write from the fork of the EB repo)
* `gist` (to create/delete gists)
The first of these reduces from the whole `repo` section to just one item.
=> Minimal scope for GitHub token

docs/Writing_easyconfig_files.rst
Puzzled over this one for a while when following the current instructions (not being familiar with using diff and patch). 
If a patch requires removal of a file, removing the file + running 'diff -ru' is not sufficient - you need to also add the N flag to get it to treat the removed file as empty which makes it be removed when patch is called.
=> Change unified diff command

docs/Deprecated-functionality.rst, docs/Hooks.rst
Also fix some typos and minor issues
=> Add documentation and example for write-module-hook

docs/Hooks.rst
fix incorrect statement I introduced in #714 🙊
=> correct statement on return value of module write hook

docs/Integration_with_GitHub.rst
Github changed its token format to be Base64 encoded now. They start with `ghp_` and end with a 6-byte checksum after a 30 "digits" of data. See https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/
I simplified the description so it applies to new and old tokens and fixed some superflous parts below ("e.g." + "etc")
=> Fix doku about Github tokens

docs/Installation.rst
Change the install instructions to avoid the bootstrap method. See #713 for an example of why.
* pip install recommended
* also eb as a module install
=> revamp EasyBuild installation docs: recommend pip or (manual) 3-stage bootstrap with pip + EasyBuild

docs/Writing_easyconfig_files.rst
In https://github.com/easybuilders/easybuild-framework/pull/3795 we changed to not allowing the git download method to get a branch, as this causes issues when we there are branchs and tags with the same name.
=> git_config tag option is for getting a tag

docs/Writing_easyconfig_files.rst
see `Example` part in https://docs.easybuild.io/en/latest/Writing_easyconfig_files.html#patches vs https://boegel-eb.readthedocs.io/en/patches_fix_format/Writing_easyconfig_files.html#patches
=> fix formatting issue in patches subsection

docs/Writing_easyconfig_files.rst
Clarify that the level must be an integer and describe the alternative to use a string to specify the starting directory. Also some minor rewording.
=> Improve the description of using a tuple in `patches`

docs/Wrapping_dependencies.rst, docs/Writing_easyconfig_files.rst
update docs to reflect https://github.com/easybuilders/easybuild-easyconfigs/issues/16330, https://github.com/easybuilders/easybuild-easyconfigs/pull/16384, https://github.com/easybuilders/easybuild-easyconfigs/pull/16386
=> update documentation to use `SYSTEM` template constant for system-toolchain dependencies

docs/Easystack-files.rst
... in accordance with https://github.com/easybuild…ers/easybuild-framework/pull/4057
Major changes: the syntax of the easystack files we support has changed. Minor changes: updated our plans for future work.
=> Updated easystack documentation 

.github/workflows/doc_build.yml, .github/workflows/linting.yml, .github/workflows/scripts.yml
Save (free) CPU hours by canceling running actions on the same branch, e.g. after a re-push on a PR
=>  Cancel GithubAction runs for outdated commits 

docs/Python-2-3-compatibility.rst
Spotted while reviewing the Mkdocs porting of this page (https://github.com/easybuilders/easybuild-docs/pull/70)
=> fix typo on Python 2 vs 3 page

docs/Easystack-files.rst
The examples with the additional `options` don't work, e.g. the first one from https://docs.easybuild.io/en/latest/Easystack-files.html#combining-command-line-options-with-options-in-an-easystack-file results in:
```
ERROR: Failed to parse easystack file: expected a dictionary with one key (the EasyConfig name), instead found keys: PyTorch-1.12.0-foss-2022a-CUDA-11.7.0.eb, options, see https://docs.easybuild.io/en/latest/Easystack-files.html for documentation.
```
Looking at an example from the tests at https://github.com/easybuilders/easybuild-framework/blob/develop/test/framework/easystacks/test_easystack_easyconfigs_opts.yaml, the additional options need more indentation, and the following does indeed work:
```
easyconfigs:
- PyTorch-1.12.0-foss-2022a-CUDA-11.7.0.eb:
options:
from-pr: …
```
=> Fix indentation in Easystack examples

.github/workflows/scripts.yml, scripts/create_source_tarball.sh
Recent versions of setuptools (>= 69.0.3, not sure?) 'normalize' package names by replacing dashes with underscores, so we source tarballs like `easybuild_framework-4.9.2.tar.gz` instead of `easybuild-framework-4.9.2.tar.gz`.
The changes being made here accept both, just to stay compatible with older setuptools versions (or in case they change their mind again...)
edit: see also https://github.com/easybuilders/easybuild-easyblocks/pull/3358
=> fix `create_source_tarball.sh` script to be compatible with recent setuptools versions

setup.py
This is just to publish EasyBuild v4.9.2 on PyPI (see https://pypi.org/project/easybuild/4.9.2)
=> bump version to 4.9.2
