easybuilders/easybuild

- docs/Changelog.rst
- docs/Installation.rst
- docs/Installation_Alternative.rst
- docs/conf.py
@wpoely86, @fgeorgatos: please review
rendered version @ boegel-eb.readthedocs.org/en/develop/Installation.html and http://boegel-eb.readthedocs.org/en/develop/Installation_Alternative.html#alt-inst-methods
> add clear requirements section to installation page, fix pip install prefix

- docs/Changelog.rst
- docs/Deprecated-functionality.rst
- docs/conf.py
rendered version at https://boegel-eb.readthedocs.org/en/depr_easyblocks/Deprecated-functionality.html#mrbayes-beagle and https://boegel-eb.readthedocs.org/en/depr_easyblocks/Deprecated-functionality.html#changes-generic-easyblocks
@wpoely86: please review (cfr. https://github.com/hpcugent/easybuild-easyblocks/pull/547)
> update documentation on deprecated functionality in (generic) easyblocks

- docs/Installation.rst
- docs/conf.py
@stdweird, @wpoely86, @fgeorgatos, @rjeschmi: please review (just one of you is fine ;-))
rendered version available @ http://boegel-eb.readthedocs.org/en/enhanced_bootstrap/Installation.html
> update documentation on bootstrapping EasyBuild

- docs/Changelog.rst
- docs/Installation.rst
- docs/conf.py
rendered version available at http://boegel-eb.readthedocs.org/en/enhance_deps_docs/Installation.html#requirements and http://boegel-eb.readthedocs.org/en/enhance_deps_docs/Installation.html#dependencies
@wpoely86, @fgeorgatos: please review?
> enhance documentation w.r.t. (optional) dependencies

- docs/Changelog.rst
- docs/Installation.rst
- docs/Unit-tests.rst
- docs/conf.py
- docs/index.rst
rendered version available at http://boegel-eb.readthedocs.org/en/unit_test_docs/Unit-tests.html
> add documentation on running unit tests

- docs/Changelog.rst
- docs/Installation.rst
- docs/Installation_Alternative.rst
- docs/conf.py
accompanies https://github.com/hpcugent/easybuild-framework/pull/1193
@besserox: please review?
> update/cleanup alt-install docs

- docs/Changelog.rst
- docs/Deprecated-functionality.rst
- docs/Installation_Alternative.rst
- docs/No-longer-supported-functionality.rst
- docs/Release_notes.rst
- docs/Removed-functionality.rst
- docs/Useful-scripts.rst
- docs/Using_the_EasyBuild_command_line.rst
- docs/conf.py
- docs/index.rst
rendered versions available at:
* http://boegel-eb.readthedocs.org/en/develop/No-longer-supported-functionality.html
* http://boegel-eb.readthedocs.org/en/develop/Deprecated-functionality.html
* http://boegel-eb.readthedocs.org/en/develop/Useful-scripts.html
@fgeorgatos, @wpoely86, @rjeschmi: please review?
> add page on no longer supported functionality, document fix_broken_easyconfigs.py script

- docs/Configuration.rst
@wpoely86: please review?
rendered version @ http://boegel-eb.readthedocs.org/en/cfgfile_templates/Configuration.html#templates-and-constants-supported-in-configuration-files
> enhance documentation w.r.t. cfgfile templates

- docs/Changelog.rst
- docs/Using_the_EasyBuild_command_line.rst
- docs/conf.py
@wpoely86, @dominikborkowski: please review?
rendered version @ http://boegel-eb.readthedocs.org/en/robot_robot_paths/Using_the_EasyBuild_command_line.html#controlling-the-robot-search-path
> enhance documentation w.r.t. --robot and --robot-paths

- docs/Changelog.rst
- docs/Installation_Alternative.rst
- docs/conf.py
fix for https://github.com/hpcugent/easybuild-framework/issues/1213
> include list of EasyBuild repositories cloned by install-EasyBuild-develop.sh script

- docs/Changelog.rst
- docs/Deprecated-functionality.rst
- docs/conf.py
(rendered version coming up, readthedocs.org is failing me ATM)
@wpoely86, @JensTimmerman: please review?
> documented deprecated functionality w.r.t. error reporting

- docs/Changelog.rst
- docs/Concepts_and_Terminology.rst
- docs/Configuration.rst
- docs/Manipulating_dependencies.rst
- docs/Partial_installations.rst
- docs/Release_notes.rst
- docs/Using_the_EasyBuild_command_line.rst
- docs/Writing_easyconfig_files.rst
- docs/conf.py
- docs/index.rst
links to the rendered version of the updated page are available via the changlog entry for the `20150430.01` docs release @ http://boegel-eb.readthedocs.org/en/eb210/Changelog.html
@wpoely86: please review
> documentation updates for EasyBuild v2.1.0

- docs/Changelog.rst
- docs/Installation.rst
- docs/conf.py
rendered version at http://boegel-eb.readthedocs.org/en/20150306/Installation.html#required-modules-tool
> doc updates for EasyBuild v2.1.1

- docs/Changelog.rst
- docs/Partial_installations.rst
- docs/conf.py
relates to change in https://github.com/hpcugent/easybuild-framework/pull/1302
> mention MigrateFromEBToHMNS in section on --module-only

- docs/Changelog.rst
- docs/Submitting_jobs.rst
- docs/conf.py
- docs/index.rst
synced up with changes in https://github.com/hpcugent/easybuild-framework/pull/1008
preview available at http://boegel-eb.readthedocs.org/en/job/Submitting_jobs.html
> add documentation on --job

- docs/Configuration.rst
And make line-wrapping consistent
> Fix layout typo in Configuration.rst

- docs/Installation.rst
This is useful for people who don't want to read the full unittest documentation but still want to run the unit test example
> added some information about the unit tests

- docs/Writing_yeb_easyconfig_files.rst
now includes Python-2.7.10 example file
> updated .yeb documentation

- docs/Concepts_and_Terminology.rst
> fix outdated fallback to ConfigureMake being mentioned in concepts page

- docs/Changelog.rst
- docs/Experimental_features.rst
- docs/Packaging_support.rst
- docs/conf.py
> update docs: packaging support is stable now

- docs/Installation_Alternative.rst
fix for mistake in documentation reported by @ajdecon in #202
> fix 'module use' statements after setting up EasyBuild develop environment

- docs/Changelog.rst
- docs/Release_notes.rst
- docs/conf.py
- setup.py
preview at http://boegel-eb.readthedocs.org/en/eb270/Release_notes.html
> release EasyBuild v2.7.0 & update release notes

- docs/Installing-Lmod-without-root-permissions.rst
- docs/Release_notes.rst
cfr. https://github.com/hpcugent/easybuild-framework/issues/1719
> update installation notes for Lmod to 6.1

- docs/Installation.rst
- docs/Installation_Alternative.rst
wrapper PR for https://github.com/hpcugent/easybuild/pull/212 by @andreas-h
fixes formatting issues, adds toc on installation page, add notes in section on `easy_install` and `pip`
> add section on updating EasyBuild

- docs/Installation.rst
following an [e-mail](https://lists.ugent.be/wws/arc/easybuild/2016-04/msg00023.html) from @boegel
> DOC: instructions to update an existing install

- .gitignore
- docs/Installation.rst
> only use raw URL for bootstrap script

- docs/scripts/update-all-docs.sh
result http://caylo-easybuild.readthedocs.io/en/autodoc-overview/version-specific/Version_Specific_Overview.html
> update docscript to generate overview page

- docs/index.rst
result http://caylo-easybuild.readthedocs.io/en/api-link/#api
> add API to index page

- docs/Integration_with_GitHub.rst
> update documentation for --from-pr to reflect changes made in EasyBuild v2.9.0

- files/modules-3.2.10-tcl8.6.patch
For the Easybuild `install_eb_deps.sh`  script.
> Add patch for modules/3.2.10 to work with tcl 8.6

- docs/Configuration.rst
- docs/Using_the_EasyBuild_command_line.rst
> fix example config file incl. both  %(repositorypath)s and %(DEFAULT_ROBOT_PATHS)s

- docs/index.rst
This makes the landing page a bit more accessible (less long).
> lower depth on index page of documentation

- docs/Writing_easyconfig_files.rst
preview @ http://boegel-eb.readthedocs.io/en/iter_opts/Writing_easyconfig_files.html#list-of-configure-build-install-options
> add section on iterating over (pre){config|build|install}opts

- docs/Experimental_features.rst
- docs/RPATH-support.rst
- docs/index.rst
preview at http://boegel-eb.readthedocs.io/en/rpath_docs/RPATH-support.html
> add docs page on RPATH support (REVIEW)

- docs/Archived-easyconfigs.rst
- docs/index.rst
preview at http://boegel-eb.readthedocs.io/en/archived_easyconfigs_docs/Archived-easyconfigs.html
> add docs page on archived easyconfigs (REVIEW)

- docs/RPATH-support.rst
Thanks for pointing these out in #271 @verdurin!
> fix typos in RPATH support docs

- docs/Cray-support.rst
> fix typo, add link to eth-cscs GitHub repo

- docs/Changelog.rst
- docs/Installation.rst
- docs/conf.py
preview at http://boegel-eb.readthedocs.io/en/docs_offline_install/Installation.html#offline-bootstrapping-using-supplied-source-tarballs
> document need to download source tarballs for vsc-install & vsc-base from PyPI

- docs/Changelog.rst
- docs/Detecting_loaded_modules.rst
- docs/conf.py
- docs/index.rst
cfr. https://github.com/hpcugent/easybuild-framework/pull/2228
preview at http://boegel-eb.readthedocs.io/en/detect_loaded_modules/Detecting_loaded_modules.html
> add documentation on --detect-loaded-modules, --allow-loaded-modules and --check-ebroot-env-vars

- docs/Contributing.rst
- docs/Maintainers.rst
- docs/Unit-tests.rst
- docs/index.rst
preview at http://boegel-eb.readthedocs.io/en/reqs_maintainers/Contributing.html and http://boegel-eb.readthedocs.io/en/reqs_maintainers/Maintainers.html
> extend list of requirements for PRs, add list of maintainers

- docs/Changelog.rst
- docs/Integration_with_GitHub.rst
- docs/conf.py
~~should wait until https://github.com/easybuilders/easybuild-framework/pull/2266 is merged~~
preview @ http://boegel-eb.readthedocs.io/en/merge_pr/Integration_with_GitHub.html#merging-easyconfig-pull-requests-merge-pr
> add documentation on --merge-pr

- docs/Partial_installations.rst
This is the documentation for https://github.com/easybuilders/easybuild-framework/pull/2134
> included --backup-module documentation

- docs/Changelog.rst
- docs/Writing_easyconfig_files.rst
- docs/conf.py
(cfr. https://github.com/easybuilders/easybuild-framework/pull/2286)
preview at http://boegel-eb.readthedocs.io/en/inject_checksums/Writing_easyconfig_files.html#inject-checksums
> document --inject-checksums

- docs/Changelog.rst
- docs/Hooks.rst
- docs/conf.py
- docs/index.rst
documentation update for feature implemented in https://github.com/easybuilders/easybuild-framework/pull/2343
preview at http://boegel-eb.readthedocs.io/en/hooks_docs/Hooks.html
> document support for user-defined hooks (WIP)

- docs/version-specific/Supported_software.rst
- docs/version-specific/easyblocks.rst
- docs/version-specific/generic_easyblocks.rst
(re-generated on top of fixes in https://github.com/easybuilders/easybuild-framework/pull/2421)
> auto-update documentation for EasyBuild v3.5.2

- docs/Partial_installations.rst
going with easybuilders/easybuild-framework#2457
> add documentation for new --fetch option

- docs/Changelog.rst
- docs/Containers.rst
- docs/conf.py
cfr. https://github.com/easybuilders/easybuild-framework/pull/2483
> add documentation on --container-tmpdir

- docs/Maintainers.rst
preview @ http://boegel-eb.readthedocs.io/en/maintainers/Maintainers.html
> update list of maintainers to reflect that they now all have admin access to all EasyBuild repositories

- docs/Hooks.rst
see https://github.com/easybuilders/easybuild-framework/pull/2562
> update hooks documentation w.r.t. parse_hook & caveats

- docs/version-specific/Supported_software.rst
> fix templating issues in 'Supported software' page

- docs/Changelog.rst
- docs/Deprecated-functionality.rst
- docs/Submitting_jobs.rst
- docs/conf.py
preview at https://boegel-eb.readthedocs.io/en/slurm_job_backend/Submitting_jobs.html
>  update --job documentation to also cover support for Slurm job backend

- docs/Code_style.rst
> + --check-style mention

- docs/Maintainers.rst
Let's give @smoors the honor of merging this himself... :)
> add Samuel Moors as EasyBuild maintainer

- docs/Writing_easyconfig_files.rst
> Add link to version specific docs to basic usage

- docs/Containers.rst
updated docs for changes made in https://github.com/easybuilders/easybuild-framework/pull/2903
rendered preview at https://boegel-eb.readthedocs.io/en/containers/Containers.html
> update docs on container integration w.r.t. enhanced --containers-base-config

- docs/Concepts_and_Terminology.rst
- docs/Release_notes.rst
- docs/System_toolchain.rst
preview at https://boegel-eb.readthedocs.io/en/eb4_release_notes/Release_notes.html
> update release notes for EasyBuild v4.0

- docs/Using_external_modules.rst
see also https://github.com/easybuilders/easybuild-framework/pull/3075
> add subsection on use of wildcards in --external-modules-metadata

- docs/Changelog.rst
- docs/Release_notes.rst
- docs/conf.py
preview at https://mdc-easybuild.readthedocs.io/en/eb410_rel_notes/Release_notes.html
> update release notes for EasyBuild v4.1.0

- docs/scripts/gen_api_docs.py
- docs/scripts/gen_easyblocks_docs.py
> Make print statements work with Py3

- docs/Changelog.rst
- docs/Release_notes.rst
- docs/conf.py
preview at https://mdc-easybuild.readthedocs.io/en/eb411/Release_notes.html
> update release notes for EasyBuild v4.1.1

- docs/Maintainers.rst
> Add Fotis to maintainer list

- docs/Maintainers.rst
> add Lars as EasyBuild maintainer

- docs/Maintainers.rst
@casparvl All yours to review/merge...
> add Caspar as EasyBuild maintainer

- docs/Changelog.rst
- docs/Release_notes.rst
- docs/conf.py
- setup.py
see https://github.com/easybuilders/easybuild-framework/pull/3248 for motivation for quick v4.1.2 bugfix release...
> release EasyBuild v4.1.2

- docs/Writing_easyconfig_files.rst
> clarify usage of git_config

- docs/Easyconfigs_index.rst
- docs/index.rst
preview at https://boegel-eb.readthedocs.io/en/easyconfigs_index/Easyconfigs_index.html
> add doc page on easyconfigs index

- docs/Changelog.rst
- docs/Release_notes.rst
- docs/conf.py
preview at https://mdc-easybuild.readthedocs.io/en/eb420/Release_notes.html
> update release notes for EasyBuild v4.2.0

- docs/Changelog.rst
- docs/Release_notes.rst
- docs/conf.py
preview at https://mdc-easybuild.readthedocs.io/en/eb421/Release_notes.html
> update release notes for EasyBuild v4.2.1

- docs/Maintainers.rst
> Updated Davide Vanzo affiliation and email

- docs/Changelog.rst
- docs/Release_notes.rst
- docs/conf.py
preview at https://mdc-easybuild.readthedocs.io/en/eb422/Release_notes.html
> update release notes for EasyBuild v4.2.2

- docs/Changelog.rst
- docs/Release_notes.rst
- docs/conf.py
preview at https://mdc-easybuild.readthedocs.io/en/eb430/Release_notes.html
> update release notes for EasyBuild v4.3.0

- docs/Release_notes.rst
preview at https://mdc-easybuild.readthedocs.io/en/eb431/Release_notes.html
> update release notes for EasyBuild v4.3.1

- docs/Changelog.rst
- docs/Release_notes.rst
- docs/conf.py
> publish release notes for EasyBuild v4.3.1

- docs/Changelog.rst
- docs/Contributing.rst
- docs/Release_notes.rst
- docs/conf.py
preview at https://mdc-easybuild.readthedocs.io/en/eb432/Release_notes.html
> update release notes and changelog for EasyBuild v4.3.2 + bump version to 4.3.2

- docs/Changelog.rst
- docs/Release_notes.rst
- docs/conf.py
preview at https://mdc-easybuild.readthedocs.io/en/eb434/Release_notes.html
> update release notes and changelog for EasyBuild v4.3.4 + bump version to 4.3.4

- docs/Packaging_support.rst
> fix typo in Packaging support docs page

- docs/Changelog.rst
- docs/Release_notes.rst
- docs/conf.py
preview at https://mdc-easybuild.readthedocs.io/en/eb440/Release_notes.html
> update release notes and changelog for EasyBuild v4.4.0 + bump version to 4.4.0

- docs/Hooks.rst
> clarify return value of module write hook

- docs/Changelog.rst
- docs/Release_notes.rst
- docs/conf.py
preview at https://mdc-easybuild.readthedocs.io/en/eb441/Release_notes.html
> update release notes and changelog for EasyBuild v4.4.1 + bump version to 4.4.1

- docs/RPATH-support.rst
RPATH support has been stable for a long time now...
> remove mentions of --experimental in docs for RPATH support

- docs/Changelog.rst
- docs/Release_notes.rst
- docs/conf.py
preview at https://mdc-easybuild.readthedocs.io/en/eb442/Release_notes.html
> update release notes and changelog for EasyBuild v4.4.2 + bump version to 4.4.2

- docs/Changelog.rst
- docs/Release_notes.rst
- docs/conf.py
preview at https://mdc-easybuild.readthedocs.io/en/eb451/Release_notes.html
> update release notes and changelog for EasyBuild v4.5.1 + bump version to 4.5.1

- docs/Changelog.rst
- docs/Release_notes.rst
- docs/conf.py
preview at https://mdc-easybuild.readthedocs.io/en/eb452/Release_notes.html
> update release notes and changelog for EasyBuild v4.5.2 + bump version to 4.5.2

- docs/Maintainers.rst
> add Jasper Grimm as EasyBuild maintainer

- docs/Writing_easyconfig_files.rst
refs: https://github.com/easybuilders/easybuild-framework/pull/3412
> Add documentation for patches

- docs/Writing_easyconfig_files.rst
cfr. https://github.com/easybuilders/easybuild-framework/pull/3949
> document 'clone_into' field in git_config that can be used in 'sources' easyconfig parameter

- docs/Changelog.rst
- docs/Release_notes.rst
- docs/conf.py
edit (by @boegel): preview available at https://boegel-eb.readthedocs.io/en/eb454/Release_notes.html
> update release notes and changelog for EasyBuild v4.5.4 + bump version to 4.5.4

- docs/Writing_easyconfig_files.rst
Documentation of a framework feature that has been added in the following PR:
* https://github.com/easybuilders/easybuild-framework/pull/3976
> Added download_instructions documentation

- docs/Changelog.rst
- docs/Release_notes.rst
- docs/conf.py
preview available at https://boegel-eb.readthedocs.io/en/eb455/Release_notes.html
> update release notes and changelog for EasyBuild v4.5.5 + bump version to 4.5.5

- docs/Changelog.rst
- docs/Release_notes.rst
- docs/conf.py
edit (by @boegel): preview available at https://boegel-eb.readthedocs.io/en/eb460/Release_notes.html
> update release notes and changelog for EasyBuild v4.6.0 + bump version to 4.6.0

- docs/Changelog.rst
- docs/Release_notes.rst
- docs/conf.py
preview at https://mdc-easybuild.readthedocs.io/en/eb461/Release_notes.html
> update release notes and changelog for EasyBuild v4.6.1 + bump version to 4.6.1

- docs/Changelog.rst
- docs/Release_notes.rst
- docs/conf.py
preview at https://mdc-easybuild.readthedocs.io/en/eb462/Release_notes.html
> update release notes and changelog for EasyBuild v4.6.2 + bump version to 4.6.2

- .github/workflows/linting.yml
- setup.py
https://pypi.org/project/easybuild/4.8.1
> bump version to 4.8.1
